#!/usr/bin/env bash
# ======================================================================
# Generate the TAK PKI + firmware cert header + data packages for the
# ESP TLS CoT server. Reproducible; run from anywhere.
#
#   bash tak-pki/gen.sh
#
# Produces (all gitignored):
#   tak-pki/ca.* server.* client.*          - keys/certs (PEM)
#   tak-pki/caCert.p12 / clientCert.p12      - legacy PKCS#12 for data packages
#   src/tak_cert.h                           - server cert+key baked into firmware
#   tak-pki/dist/ESP-Drone-TAK-OmniTAK.zip   - data package for OmniTAK (ATAK-style)
#   tak-pki/dist/ESP-Drone-TAK-iTAK.zip      - data package for iTAK / TAK Aware
#
# Self-signed, local-AP dev certs. Low sensitivity, but never commit the keys.
# ======================================================================
set -euo pipefail
cd "$(dirname "$0")"
ROOT=".."

IP=192.168.4.1          # must match the SoftAP IP / server cert SAN
PORT=8089               # TLS CoT port (COT_TLS_PORT in tak.cpp)
PASS=atakatak           # data-package cert password (TAK convention)
DAYS=3650

if [ -f ca.crt ] && [ -f server.crt ] && [ -f client.crt ] && [ -f server.key ]; then
  echo "== reusing existing CA/server/client certs (delete tak-pki/*.crt to regenerate) =="
else
  echo "== CA =="
  openssl req -x509 -newkey rsa:2048 -keyout ca.key -out ca.crt -days $DAYS -nodes \
    -subj "/CN=ESP-Drone-TAK-CA"

  echo "== server cert (CN/SAN=$IP) =="
  openssl req -newkey rsa:2048 -keyout server.key -out server.csr -nodes -subj "/CN=$IP"
  printf "subjectAltName=IP:%s\nextendedKeyUsage=serverAuth\n" "$IP" > server.ext
  openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
    -out server.crt -days $DAYS -extfile server.ext

  echo "== client cert =="
  openssl req -newkey rsa:2048 -keyout client.key -out client.csr -nodes -subj "/CN=esp-drone-client"
  printf "extendedKeyUsage=clientAuth\n" > client.ext
  openssl x509 -req -in client.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
    -out client.crt -days $DAYS -extfile client.ext
fi

echo "== PKCS#12 bundles (legacy 3DES/SHA1 — required for iTAK to read them) =="
openssl pkcs12 -export -nokeys -in ca.crt -out caCert.p12 -passout pass:$PASS -name caCert \
  -certpbe PBE-SHA1-3DES -keypbe PBE-SHA1-3DES -macalg sha1 -legacy
openssl pkcs12 -export -in client.crt -inkey client.key -out clientCert.p12 -passout pass:$PASS \
  -name espdrone -certpbe PBE-SHA1-3DES -keypbe PBE-SHA1-3DES -macalg sha1 -legacy

echo "== firmware header src/tak_cert.h =="
python3 - "$ROOT" <<'PY'
import sys
root = sys.argv[1]
crt = open("server.crt").read().strip()
key = open("server.key").read().strip()
with open(root + "/src/tak_cert.h", "w") as f:
    f.write("#pragma once\n")
    f.write("// Self-signed TAK server cert+key for the ESP TLS CoT server.\n")
    f.write("// Generated by tak-pki/gen.sh. Local-AP dev cert; the matching truststore\n")
    f.write("// ships in the TAK data package. Do NOT commit this file (contains the key).\n\n")
    f.write('static const char TAK_SERVER_CERT[] = R"CERT(\n' + crt + '\n)CERT";\n\n')
    f.write('static const char TAK_SERVER_KEY[] = R"KEY(\n' + key + '\n)KEY";\n')
print("  wrote src/tak_cert.h")
PY

UUID1=$(uuidgen); UUID2=$(uuidgen)
mkdir -p dist

# ---- OmniTAK / ATAK-style package: certs in cert/, numbered keys, MANIFEST/ ----
echo "== data package: OmniTAK (ATAK-style) =="
rm -rf build_omni && mkdir -p build_omni/MANIFEST build_omni/cert
cp caCert.p12 clientCert.p12 build_omni/cert/
cat > build_omni/esp-drone.pref <<PREF
<?xml version='1.0' encoding='ASCII' standalone='yes'?>
<preferences>
  <preference version="1" name="cot_streams">
    <entry key="count" class="class java.lang.Integer">1</entry>
    <entry key="description0" class="class java.lang.String">ESP Drone TAK</entry>
    <entry key="enabled0" class="class java.lang.Boolean">true</entry>
    <entry key="connectString0" class="class java.lang.String">$IP:$PORT:ssl</entry>
    <entry key="caLocation0" class="class java.lang.String">cert/caCert.p12</entry>
    <entry key="caPassword0" class="class java.lang.String">$PASS</entry>
    <entry key="certificateLocation0" class="class java.lang.String">cert/clientCert.p12</entry>
    <entry key="clientPassword0" class="class java.lang.String">$PASS</entry>
    <entry key="useAuth0" class="class java.lang.Boolean">false</entry>
  </preference>
</preferences>
PREF
cat > build_omni/MANIFEST/manifest.xml <<MAN
<MissionPackageManifest version="2">
  <Configuration>
    <Parameter name="uid" value="$UUID1"/>
    <Parameter name="name" value="ESP-Drone-TAK-OmniTAK"/>
    <Parameter name="onReceiveDelete" value="false"/>
  </Configuration>
  <Contents>
    <Content ignore="false" zipEntry="cert/caCert.p12"/>
    <Content ignore="false" zipEntry="cert/clientCert.p12"/>
    <Content ignore="false" zipEntry="esp-drone.pref"/>
  </Contents>
</MissionPackageManifest>
MAN
( cd build_omni && rm -f ../dist/ESP-Drone-TAK-OmniTAK.zip && \
  zip -r -X ../dist/ESP-Drone-TAK-OmniTAK.zip cert esp-drone.pref MANIFEST >/dev/null )

# ---- iTAK / TAK Aware package: flat root, NON-numbered keys in ----
# ---- com.atakmap.app_preferences, root manifest.xml ----
echo "== data package: iTAK / TAK Aware =="
rm -rf build_itak && mkdir -p build_itak
cp caCert.p12 clientCert.p12 build_itak/
cat > build_itak/defaults.pref <<PREF
<?xml version='1.0' encoding='ASCII' standalone='yes'?>
<preferences>
  <preference version="1" name="cot_streams">
    <entry key="count" class="class java.lang.Integer">1</entry>
    <entry key="description0" class="class java.lang.String">ESP Drone TAK</entry>
    <entry key="enabled0" class="class java.lang.Boolean">true</entry>
    <entry key="connectString0" class="class java.lang.String">$IP:$PORT:ssl</entry>
    <entry key="useAuth0" class="class java.lang.Boolean">false</entry>
  </preference>
  <preference version="1" name="com.atakmap.app_preferences">
    <entry key="caLocation" class="class java.lang.String">caCert.p12</entry>
    <entry key="caPassword" class="class java.lang.String">$PASS</entry>
    <entry key="certificateLocation" class="class java.lang.String">clientCert.p12</entry>
    <entry key="clientPassword" class="class java.lang.String">$PASS</entry>
    <entry key="displayServerConnectionWidget" class="class java.lang.Boolean">true</entry>
  </preference>
</preferences>
PREF
cat > build_itak/manifest.xml <<MAN
<MissionPackageManifest version="2">
  <Configuration>
    <Parameter name="uid" value="$UUID2" />
    <Parameter name="name" value="ESP-Drone-TAK-iTAK" />
  </Configuration>
  <Contents>
    <Content zipEntry="caCert.p12" ignore="false" />
    <Content zipEntry="clientCert.p12" ignore="false" />
    <Content zipEntry="defaults.pref" ignore="false" />
  </Contents>
</MissionPackageManifest>
MAN
( cd build_itak && rm -f ../dist/ESP-Drone-TAK-iTAK.zip && \
  zip -X ../dist/ESP-Drone-TAK-iTAK.zip caCert.p12 clientCert.p12 defaults.pref manifest.xml >/dev/null )

rm -rf build_omni build_itak
echo
echo "== done =="
echo "  src/tak_cert.h  (rebuild firmware to embed it)"
echo "  dist/ESP-Drone-TAK-OmniTAK.zip   -> import into OmniTAK"
echo "  dist/ESP-Drone-TAK-iTAK.zip      -> import into iTAK / TAK Aware"
